### ISSUE TITLE
If you create a redstone circuit using Tripwire Hook, it will count more.

### ISSUE THREAD

**Issue by NamiUni** [InsightsPlugin/Insights#162]
See the video for details.

https://user-images.githubusercontent.com/53502121/155865606-1c54b3f8-7b4c-4d2c-8228-c634c869e509.mp4

**Comment by NamiUni** [comment]
```yaml
# This is an example group limit for tiles. Users will be able to place at most 64 redstone in a chunk.
# The limit makes use of a world blacklist, which means with the current configuration it will work for all worlds.
# It will also work for all addons.
limit:
  name: "レッドストーン回路"
  type: "GROUP"
  bypass-permission: "insights.bypass.limit.redstone"
  limit: 64
  materials:
    - "HOPPER"
    - "DISPENSER"
    - "DROPPER"
    - "TRIPWIRE_HOOK"
    - "STICKY_PISTON"
    - "PISTON"
    - "TNT"
    - "NOTE_BLOCK"
    - "REPEATER"
    - "COMPARATOR"
  settings:
    enabled-worlds:
      whitelist: false
      worlds: []
    enabled-addons:
      whitelist: false
      addons: []
```
