### ISSUE TITLE
Players cannot place other restricted blocks after hitting any limit

### ISSUE THREAD

**Issue by blockswerker** [InsightsPlugin/Insights#166]
Hello, first let me say this is a great plug-in that I already consider to be essential even though my server only been using it for a couple of days. I'm not sure if I've found a bug or not, but the behavior I've observed is unexpected to me.

Steps to Reproduce:

1. Create two rules: one that limits the number of chests (10), another that limits the number of e-tables (10).
2. Fill a chunk to the max. # of chests. Then try to place an e-table.
3. Observe that even though the limit on e-tables has not been exceeded, the player cannot place that block until a chest is removed.
4. Try to place a shulker. Observe that even though the shulker is not a limited block that the plugin cancels the placement.

Is that intended behavior? Is there a config setting or permission that I have misunderstood? Thanks for your help!

**Comment by blockswerker** [comment]
I think you're right, I probably don't understand how tiles work in Insights. I have this limit file:

```
limit:
  name: "FPSBan_Tiles"
  type: "TILE"
  bypass-permission: "insights.bypass.limit.fpsban"
  limit: 5
  materials:
    - "ENCHANTING_TABLE"
    - "CAMPFIRE"
    - "SOUL_CAMPFIRE"
```

And this one:
```
limit:
  name: "Chests"
  type: "TILE"
  bypass-permission: "insights.bypass.limit.chests"
  limit: 10
  materials:
    - "CHEST"
    - "TRAPPED_CHEST"
    - "BARREL"
```
Is "TILE" the wrong kind? Perhaps it should be "GROUP"?
