### ISSUE TITLE
Bug with WorldEdit addon

### ISSUE THREAD

**Issue by NoltoxGit** [InsightsPlugin/Insights#167]
Hello!
I'm using the WorldEdit addon, and I set the `disable-tiles` value to `false`, because players can't copy paste sign.

However, even with this value the problem persists, can someone please tell me a solution to the problem?

and also try with `use-limits : false` and nothing change, players always see the message defined by the plugin.

Config InsightsWE:
```yml
settings:
  type: REPLACEMENT
  replacement-block: AIR
  use-limits: true
  disable-tiles: false
  extra-blocked:
    whitelist: false
    materials:
    - SCULK_SENSOR
messages:
  summary:
    header: ''
    format: ''
    unchanged: '&x&7&d&d&f&5&2&lPerformances &8» &x&c&c&c&c&c&cEmpêché un total de
      &x&e&6&d&5&4&5%count% &x&c&c&c&c&c&cblocs d''être placés.'
    replaced: '&x&7&d&d&f&5&2&lPerformances &8» &x&c&c&c&c&c&cUn total de &x&e&6&d&5&4&5%count%
      &x&c&c&c&c&c&cblocs ont été remplacés par &x&e&6&d&5&4&5%replacement%&x&c&c&c&c&c&c.'
    footer: ''
 ```

~ Noltox ~
