### ISSUE TITLE
Chunk and area limits can't be used simultaneously

### ISSUE THREAD

**Issue by UDPSendToFailed** [InsightsPlugin/Insights#172]
I'm trying to set up the limits so the players are both denied from placing specific block(s) outside of regions, and also being limited inside regions on per chunk basis.

A simple example of what I'm trying to achieve:

- The player should not be able to place hopper outside of their region (GP for example).
- The player should be limited on how much hoppers they can place inside their region.
- The limitation should apply on per chunk basis inside the player's region (8 hoppers / chunk for example).

I've tried messing with the options in the limitation files, so far this is the closest I can get to the expected result:

- The player is denied from placing hoppers outside of their region, but also the limit of 8 hoppers applies to the whole region instead of being applied on per chunk basis inside the region.

```
limit:
  name: "Hopper"
  type: "GROUP"
  bypass-permission: "insights.bypass.limit.hopper"
  limit: 8
  materials:
    - HOPPER
  settings:
    enabled-worlds:
      whitelist: false
      worlds: []
    enabled-addons:
      whitelist: true
      addons:
        - GriefPrevention
    disallow-placement-outside-region: true
```

Versions:

- Insights 6.12.1-SNAPSHOT
- GriefPreventionAddon 2.1.0
- GriefPrevention 16.18
