### ISSUE TITLE
Tripwire not getting recognized 

### ISSUE THREAD

**Issue by LuluxClient** [InsightsPlugin/Insights#185]
I'm trying to create a limit of 64 tripwire per chunk but it is not working: 

```
# This is an example group limit for tiles. Users will be able to place at most 64 redstone in a chunk.
# The limit makes use of a world blacklist, which means with the current configuration it will work for all worlds.
# It will also work for all addons.
limit:
  name: "String"
  type: "GROUP"
  bypass-permission: "insights.bypass.limit.string"
  limit: 64
  materials:
    - "PLAYER_HEAD"
    - "TRIPWIRE"
    - "LEGACY_TRIPWIRE"
    - "TRIPWIRE_HOOK"
    - "STRING"
    - "PLAYER_WALL_HEAD"
  settings:
    enabled-worlds:
      whitelist: false
      worlds: []
    enabled-addons:
      whitelist: false
      addons: []
    disallow-placement-outside-region: false

```

I don't have any addon installed and I'm on 1.19.2 and when scanning the chunk I see this: 
![image](https://user-images.githubusercontent.com/62576432/203953812-63a647ea-8955-477e-910e-19fae8bd8bd0.png)
so there is nothing wrong with my configuration (I think)
