### ISSUE TITLE
Different entities do not work

### ISSUE THREAD

**Issue by LutrexMC** [InsightsPlugin/Insights#202]
Some files with limits I designed won't load because some entities won't go...
This error comes with a mushroom cow:
```
[17:25:35 ERROR]: [Insights] Limit 'animals-limit.yml' could not be loaded:
[17:25:35 ERROR]: [Insights] File 'animals-limit.yml' at path 'limit.entities': 'MOOSHROOM' is not a valid entity!
```

## My configuration:
```
limit:
  name: "Tiere"
  type: "GROUP"
  bypass-permission: "insights.bypass"
  limit: 200
  entities:
    - "AXOLOTL"
    - "BAT"
    - "BEE"
    - "CAMEL"
    - "CAT"
    - "CHICKEN"
    - "COD"
    - "COW"
    - "DOLPHIN"
    - "DONKEY"
    - "FOX"
    - "FROG"
    - "GLOW_SQUID"
    - "GOAT"
    - "HORSE"
    - "LLAMA"
    - "MOOSHROOM"
    - "MULE"
    - "OCELOT"
    - "PANDA"
    - "PARROT"
    - "PIG"
    - "POLAR_BEAR"
    - "PUFFERFISH"
    - "RABBIT"
    - "SALMON"
    - "SHEEP"
    - "SNIFFER"
    - "SQUID"
    - "TADPOLE"
    - "TROPICAL_FISH"
    - "TURTLE"
    - "WOLF"
  settings:
    enabled-worlds:
      whitelist: true
      worlds: [Plotwelt]
    enabled-addons:
      whitelist: false
      addons: []
    disallow-placement-outside-region: false
```

### Also, boats don't go either:
```
[17:25:35 ERROR]: [Insights] Limit 'boat-limit.yml' could not be loaded:
[17:25:35 ERROR]: [Insights] File 'boat-limit.yml' at path 'limit.entities': 'OAK_BOAT' is not a valid entity!
```

**/version** 
_This server is running Paper version git-Paper-131 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 307d05b)
You are running the latest version
Previous version: git-Pufferfish-3 (MC: 1.20.1)_
