### ISSUE TITLE
Feature request: Update check masking

### ISSUE THREAD

**Issue by SlimeDog** [InsightsPlugin/Insights#59]
I hope that if update checking is reintroduced (in 6.0.0 or later) that the options to disable them are also reincorporated into `config.yml` (taken from 5.9.3 version):
```
general:
  # The update section of Insights!
  updates:
    # Disable this is you don't want any notifications about updates
    # of Insights. Insights will check the GitHub repo for updates.
    # Permission to receive updates: insights.notification.update
    check: true
    # Choose whether you want Insights to automatically install updates!
    # Not recommended for production servers, always carefully test before updating!
    download: false
    # If you really want to ensure you're always on the latest version of Insights
    # without touching anything, you can enable this setting below. This will
    # enable Insights to download and restart the plugin on startup of the server.
    download_startup: false
```
