### ISSUE TITLE
Enhancement: Add exceptions to group limits

### ISSUE THREAD

**Issue by Danielpeter-99** [InsightsPlugin/Insights#87]
Would be nice to add exceptions to some limitations determined by groups, example:
```
limit:
  name: "Tiles"
  type: "TILE"
  bypass-permission: "insights.bypass.limit.tile"
  limit: 256
  settings:
    **exceptions: CHEST**
    enabled-worlds:
      whitelist: false
      worlds: []
    enabled-addons:
      whitelist: false
      addons: []
```
